sdk: '2'
language: bash
go-runtime:
  version: '1.10-alpine'
native:
  image: 'openjdk:8-jre-alpine'
  static:
      - path: src/main/sh/native.sh
        dest: native
  deps:
      - 'apk add gradle'
  build:
    image: 'openjdk:8-slim'
    deps:
      - 'apt-get update && apt-get install -y make bash wget gradle'
    run:
      - 'make'
      - 'gradle shadowJar'
    artifacts:
      - path: '/native/build/libs/native-jar-with-dependencies.jar'
  test:
    run:
      - 'echo test'
      # XXX download and use gradle 4.9 since alpine version is bugged
      # for tests
      #- 'make'
      #- 'gradle test --stacktrace'
