sdk: '2'
language: bash
go-runtime:
  version: '1.10-alpine'
native:
  image: 'openjdk:8-jre-alpine'
  static:
      - path: src/main/sh/native.sh
        dest: native
  build:
    image: 'openjdk:8-slim'
    deps:
      - 'apt-get update && apt-get install -y make bash wget gradle'
    run:
      - 'make'
      - 'gradle shadowJar'
    artifacts:
      - path: '/native/build/libs/native-jar-with-dependencies.jar'
  test:
    run:
      # download and use gradle 4.9 since alpine's version is bugged for tests
      - 'wget https://services.gradle.org/distributions/gradle-4.9-bin.zip'
      - 'unzip -o gradle-4.9-bin.zip'
      - 'gradle-4.9/bin/gradle test --info --stacktrace'
      - 'rm -rf gradle-4.9*'
